### ISSUE TITLE
Seperate scenes for each terrains?

### ISSUE THREAD

**Issue by sre42** [brsaylor/wobspring2015#13]
currently, the team is trying to instantiate the terrain and then create runtime prefabs, following are the concerns.
Is the instantiated terrain pre-baked? if not then we may need like 5 prepared scenes, and then call each scene upon type of terrain.(which is what unity tutorials:game levels suggested).

Also, here is the article that says why spawning prefabs is better than programming them at runtime:
http://docs.unity3d.com/Manual/InstantiatingPrefabs.html

**Comment by dkushner** [comment]
We're instantiating the terrains as prefabs. We have pre-configured terrain prefabs with set names that  we just throw into the scene depending on the terrain string we get back from the server. Is this causing problems?
