### ISSUE TITLE
RequestClashPlayerView has either a misnamed member or is using an incorrect method.

### ISSUE THREAD

**Issue by dkushner** [brsaylor/wobspring2015#2]
In RequestClashPlayerView, we call the following line:

```
Player player = PlayerDAO.getPlayerByAccount(playerID);
```

Where playerID is a member of the request class. Is this intended? Either fix the name of the member or use `PlayerDAO.getPlayer(playerID)`.

**Comment by brsaylor** [comment]
It should probably be PlayerDAO.getPlayer(playerID), since we're dealing with Players, not Accounts.
