### ISSUE TITLE
Allow instantiating multiples of each species

### ISSUE THREAD

**Issue by brsaylor** [brsaylor/wobspring2015#30]

**Comment by Rotoscope** [comment]
What's the limit? 
The code to do this is simple. 
Remove the toggle disable in the raycast code block.

For every instantiation, decrease a count and when it hits 0, disable the toggle.

Will we need to send this limit be stored in the attackconfig in the server?

What about the defense? 
Should we even consider the placement of the defense anymore?
Should we just store the amount of each of the 5 unique units and spawn the defense randomly on the terrain mask?

**Comment by brsaylor** [comment]
Let's define a constant for the limit and try 3 to start.
It would provide more opportunity for strategy if we allow defending units to be placed by the player. I've also just changed the DB, DAO, and model to store the positions of multiple units per species; on to the protocol next.

**Comment by brsaylor** [comment]
Protocols are updated on the server side to work with the new DefenseConfig model. They still need to be modified on both the client and server side to actually allow multiple species.
