### ISSUE TITLE
Clean up unused files for ClashBattle

### ISSUE THREAD

**Issue by ssammi** [brsaylor/wobspring2015#34]
I think we only need 3 scripts for Battle:  ClashBattleController , ClashBattleToggle, ClashBattleUnit.

All other folders and prefabs(button) can be delete 

Those 2 folders are our 2 copy of old AIs, and canvas and button prefab are also for our old clash battle. 

we dont need gameOverController and the animController.cs . we dont need these two as well.

**Comment by Rotoscope** [comment]
Do we need the terrain assets in Assets/ClashOfSpecies/ anymore?
We already have the prefabs of the terrains so we might be able to delete that folder.

Can we move the Assets/Resources/ClashOfSpecies/ items to the appropriate folders?
Like Assets/Resources/ClashOfSpecies/Animators/ to:
Assets/Resources/Animators/ClashOfSpecies/

and the Models to the Assets/Resources/Models/ClashOfSpecies/

There are models in Assets/Resources/Models/. Are they used?
If they are, then can we move them to a ClashOfSpecies subdirectory?

Is the folder:  Assets/Resources/Prefabs/3dModels/ ours?
If they are, can we move them to:
Assets/Resources/Models/ClashOfSpecies/
or
Assets/Resources/Models/ClashOfSpecies/3dModels

Delete empty folder:
3D Animal Prefabs/ and Unit/ inside:
Assets/Resources/Prefabs/ClashOfSpecies/

**Comment by Rotoscope** [comment]
Assets/Resources/Prefabs/ClashOfSpecies/Defense/DefenseItem.prefab
and its meta file is not used anymore.

Might want to consider moving:
Assets/Resources/Prefabs/ClashOfSpecies/Defense/UnitListItem.prefab
and its meta file out. It is the the toggle prefab for both the defense setup and the battle

**Comment by Rotoscope** [comment]
Are we using anything in the folder:
Assets/Resources/Prefabs/ClashOfSpecies/battle/

**Comment by Rotoscope** [comment]
In scripts:
Can delete:
ClashGetActiveToggle.cs
ClashStatusText.cs
ResultMenu.cs
Unit/
Unit/ClashUnitAttributes.cs
Unit/ClashUnitAI.cs
Unit/ClashNavMeshAI.cs
Main/ClashPreviewController.cs
Camera/ClashDefenseSpawner.cs
Camera/ClashCameraControl.cs
Camera/ClashBattleSpawner.cs
